// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq3irzoYiLKFlsw_UIwMP55Y_BUWOM7Hg',
    appId: '1:549067874062:web:1087d76d18d85b088f015f',
    messagingSenderId: '549067874062',
    projectId: 'riega-me',
    authDomain: 'riega-me.firebaseapp.com',
    storageBucket: 'riega-me.firebasestorage.app',
    measurementId: 'G-JGVPXZRRTJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASqN90aGHeHDTLbMEh16c1YVABH_XYlAY',
    appId: '1:549067874062:android:51c086914dc362a68f015f',
    messagingSenderId: '549067874062',
    projectId: 'riega-me',
    storageBucket: 'riega-me.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAilgTciBT9SCobi9nGjZ7CSh15ZByvDpQ',
    appId: '1:549067874062:ios:1319cc12ef266d3d8f015f',
    messagingSenderId: '549067874062',
    projectId: 'riega-me',
    storageBucket: 'riega-me.firebasestorage.app',
    iosBundleId: 'com.example.riegaMe',
  );

}